hmsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, add_book_page, detail_book_page, delete_book, update_book_page, similarity_checker


app_name = "main"
urlpatterns = [
    path('', index, name='home'),
    path('add-book/', add_book_page, name='add-book'),
    path('detail-book/<int:id>', detail_book_page, name='detail-book'),
    path('delete-book/<int:id>', delete_book, name='delete-book'),
    path('update-book/<int:id>', update_book_page, name='update-book'),
    path('similarity-checker/', similarity_checker, name='similarity-checker')
]

main/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

main/forms.py
from django.forms import ModelForm
from .models import Book, Publisher, Author

class BookForm(ModelForm):
    def save(self, author=None, publisher=None, commit=True):

        title = self.cleaned_data.get('title')
        pub_date = self.cleaned_data.get('publication_date')

        book = Book(title=title, publication_date=pub_date, publisher=publisher)
        book.save()
        if commit:
            book.authors.set([author,])
        return book
    class Meta:
        model = Book
        fields = ['title', 'publication_date']

class PublisherForm(ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BookForm, AuthorForm, PublisherForm
from .models import Book

# Create your views here.

def index(request):
    books = Book.objects.all()
    authors = [[author for author in book.authors.all()] for book in books ]

    # nested loop regular version

    # authors = []
    # for book in books:
    #     author_lst = []
    #     for author in book.authors.all():
    #         author_lst.append(author)
    #     author_lst.append(author_lst)

    books_render = {}
    for i in range(len(books)):
        books_render[books[i]] = authors[i]
    print(books_render)


    context = {
        'page_title' : 'Home',
        'books': books_render,
    }
    return render(request, 'home.html', context)

def add_book_page(request):
    book_form = BookForm()
    author_form = AuthorForm()
    publisher_form = PublisherForm()
    
    if request.method == "POST":
        book_form = BookForm(data=request.POST)
        author_form = AuthorForm(data=request.POST)
        publisher_form = PublisherForm(data=request.POST)
        
        print("masuk ke if method")

        if book_form.is_valid() and publisher_form.is_valid() and author_form.is_valid():
            author = author_form.save()
            publisher = publisher_form.save()
            book = book_form.save(author=author, publisher=publisher)
            return redirect('main:home')
        else:
            print('masuk ke else not valid')
            print(book_form.is_valid())
            print(publisher_form.is_valid())
            print(author_form.is_valid())
            book_form = BookForm()
            author_form = AuthorForm()
            publisher_form = PublisherForm()
    
    context = {
        'page_title': 'Add Book',
        'book_form': book_form,
        'author_form': author_form,
        'publisher_form': publisher_form
    }

    return render(request, 'add-book.html', context)


def detail_book_page(request, id):
    book = Book.objects.get(id=id)
    context = {
        'page_title' : 'Detail Book',
        'book_title' : book.title,
        'book_id' : book.id,
        'book_pub_date' : book.publication_date,
        'book_authors' : [author for author in book.authors.all()],
        'publisher' : book.publisher
    }

    return render(request, 'detail-book.html', context)


def delete_book(request, id):
    Book.objects.get(id=id).delete()
    return redirect('main:home')


def update_book_page(request, id):
    book = get_object_or_404(Book, id=id)
    book_form = BookForm(initial={'title': book.title, 'publication_date': book.publication_date})

    if request.method == "POST":
        book_form = BookForm(data=request.POST, instance=book)
        if book_form.is_valid():
            book.title = book_form.cleaned_data.get('title')
            book.publication_date = book_form.cleaned_data.get('publication_date')
            book.save()
            return redirect('main:home')
        else:
            book_form = BookForm(initial={'title': book.title, 'publication_date': book.publication_date})


    context = {
        'page_title': "Update Book's Info",
        'book_form': book_form,
        'book_id': id,
    }

    return render(request, 'update-book.html', context)


def similarity_checker(request):
    context = {
        'page_title': 'Similarity Checker'
    }

    return render(request, 'similarity-checker.html', context)

main/templates/add-book.html
{% extends 'landing/base.html' %}

{% block style %}

{% endblock style %}


{% block content %}

<div class="container">
    <br>
    <h3>Add a new book here...</h3>
    <br>
    <form action="{% url 'main:add-book' %}" method="POST">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <label for="titleInput">Title:</label>
                {{book_form.title}}
            </div>
            <div class="col">
                <label for="publicationDateInput">Publication Date (format:dd/mm/yyyy):</label>
                {{book_form.publication_date}}
            </div>

        </div>
        <br>
        <h5>About the author</h5>
        <div class="row">
            <div class="col">
                <label for="firstNameInput">First Name:</label>
                {{author_form.first_name}}
            </div>
            <div class="col">
                <label for="lastNameInput">Last Name:</label>
                {{author_form.last_name}}
            </div>
            <div class="col">
                <label for="emailInput">Email:</label>
                {{author_form.email}}
            </div>
        </div>

        <br>
        <h5>About the publisher</h5>
        <div class="row">
            <div class="col">
                <label for="nameInput">Name:</label>
                {{publisher_form.name}}
            </div>
            <div class="col">
                <label for="addressInput">Address:</label>
                {{publisher_form.address}}
            </div>
            <div class="col">
                <label for="cityInput">City:</label>
                {{publisher_form.city}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="stateProvinceInput">State Province:</label>
                {{publisher_form.state_province}}
            </div>
            <div class="col">
                <label for="countryInput">Country:</label>
                {{publisher_form.country}}
            </div>
            <div class="col">
                <label for="websiteInput">Website:</label>
                {{publisher_form.website}}
            </div>
        </div>
        <br>
        <div class="text-right">
            <button class="btn btn-success" type="submit">Submit</button>
        </div>

    </form>
</div>
{% endblock content %}

{% block script %}

<script>
    document.getElementById('id_publication_date').classList.add('form-control')
    document.getElementById('id_publication_date').type = "date"
    document.getElementById('id_title').classList.add('form-control')
    document.getElementById('id_first_name').classList.add('form-control')
    document.getElementById('id_last_name').classList.add('form-control')
    document.getElementById('id_email').classList.add('form-control')
    document.getElementById('id_city').classList.add('form-control')
    document.getElementById('id_name').classList.add('form-control')
    document.getElementById('id_website').classList.add('form-control')
    document.getElementById('id_country').classList.add('form-control')
    document.getElementById('id_address').classList.add('form-control')
    document.getElementById('id_state_province').classList.add('form-control')
</script>
{% endblock script %}

main/templates/detail-book.html
{% extends 'landing/base.html' %}


{% block style %}


{% endblock style %}


{% block content %}
<div class="container">
    <br>

    <h2>{{ book_title }}</h2>
    <p>first published at {{book_pub_date}}</p>
    <br>

    <h4>The author(s):</h4>
    {% for author in book_authors %}
        <ul>
            <li>
                <p>
                    {{ author.first_name }} {{ author.last_name }} ({{author.email}})
                </p>
            </li>
        </ul>
    {% endfor %}
    <br>
    <h4>The publisher:</h4>
    <p>Name : {{publisher.name}}</p>
    <p>Address : {{publisher.address}}, {{publisher.city}}, {{publisher.state_province}}, {{publisher.country}}</p>
    <p>Website : <a href="{{publisher.website}}">{{publisher.website}}</a></p>

    <div class="row">
        <div class="col-auto">
            <a href="{% url 'main:update-book' book_id %}" class="btn btn-primary">Edit</a>
        </div>
        <div class="col-auto">
            <a href="{% url 'main:delete-book' book_id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}


{% endblock script %}

main/templates/home.html
{% extends 'landing/base.html' %}

{% block style %}
<style>
    .card {
        margin-bottom: 10px;
    }
    .title-bookfinder{
        color: steelblue;
    }
</style>

{% endblock style %}


{% block content %}

<div class="container">
    <br>
    <h1 class="text-center">Welcome to <span class="title-bookfinder">Bookfinder.in</span></h1>
    <h4 class="text-center">find your favorite book's information here...</h4>
    <br>
    <hr>
    <div class="row">
        {% for book, authors in books.items %}
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">
                        A book by {% for author in authors %} {{author.first_name}} {{author.last_name}}, {% endfor %} published at {{book.publication_date}}
                    </p>
                    <a href="/detail-book/{{book.id}}" class="btn btn-primary">See details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block script %}
{% endblock script %}

main/templates/landing/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    {% load static %}

    {% block style %}

    {% endblock style %}
    <style>
        #title-navbar {
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
            font-size: x-large;
        }

        body {
            font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
            /* font-size: large; */

        }
    </style>

    <title>{{page_title}}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/" id="title-navbar">
                Bookfinder.in
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/add-book/">add book</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link" href="/similarity-checker/">similarity checker</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link" href="https://github.com/muhrianal/hmsite">repository</a>
                </div>
            </div>
            
        </div>

    </nav>

    {% block content %}

    {% endblock content %}



    {% block script %}

    {% endblock script %}
</body>

</html>

main/templates/similarity-checker.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="container">
    <br>

    <h1>Similarity checker</h1>
    <p>This feature will accept two inputs string, then the program will check how many percent of the characters in the first input also appear in the second one</p>

    <div class="form-group">
        <div class="row">
            <div class="col">
                <input type="text" class="form-control" name="inputOne" id="inputOne" placeholder="First string">
            </div>
            <div class="col">
                <input type="text" class="form-control" name="inputTwo" id="inputTwo" placeholder="Second string">
            </div>
        </div>
        <br>
        <h5 id="message"></h5>
        
        <button class="btn btn-primary" id="btn-check">Check</button>
    </div>
</div>

{% endblock content %}

{% block script %}
<script>
    document.getElementById("btn-check").onclick = function() { checkSimilarity() }

    function checkSimilarity(){
        var inputOne = document.getElementById("inputOne").value
        var inputTwo = document.getElementById("inputTwo").value

        var count = 0
        for (var i = 0; i < inputOne.length; i++){
            if (inputTwo.toLowerCase().includes(inputOne.charAt(i).toLowerCase())){
                count++
            }
        }
        var percentage = (count/inputOne.length) * 100
        
        document.getElementById('message').innerHTML = `There are ${percentage}% character(s) in first input (${inputOne}) appear in second input (${inputTwo})`
    }

</script>



{% endblock script %}

main/templates/update-book.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="container">
    <br>

    <form action="{% url 'main:update-book' book_id %}" method="POST">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                <label for="titleInput">Title:</label>
                {{book_form.title}}
            </div>
            <div class="col">
                <label for="publicationDateInput">Publication Date (format:dd/mm/yyyy):</label>
                {{book_form.publication_date}}
            </div>
        </div>
        <br>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>

</div>

{% endblock content %}

{% block script %}
<script>
    document.getElementById('id_publication_date').classList.add('form-control')
    document.getElementById('id_publication_date').type = "date"
    document.getElementById('id_title').classList.add('form-control')
</script>

{% endblock script %}